- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: docker-ce

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Get the latest Docker Compose version
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: yes
  register: compose_release

- name: Set Docker Compose version
  set_fact:
    compose_version: "{{ compose_release.json.tag_name }}"

- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create a symbolic link for docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link