- name: Install pip
  dnf:
    name: python3-pip
    state: present

- name: Install python3-libselinux
  dnf:
    name: python3-libselinux
    state: present

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Put SELinux in Permissive Mode
  ansible.posix.selinux:
    state: permissive

- name: Install some packages
  dnf:
    name:
      - htop
      - nano
    state: present